new_dict = {}
old_dict = {
  "53": "Washginton",
  "41": "Oregon",
  "16": "Idaho",
  "32": "Nevada",
   "6": "California",
  "49": "Utah",
   "4": "Arizona",
  "30": "Montana",
  "56": "Colorado",
   "8": "Wyoming",
  "35": "New Mexico",
  "38": "North Dakota",
  "46": "South Dakota",
  "31": "Nebraska",
  "20": "Kansas",
  "40": "Oklahoma",
  "48": "Texas",
  "27": "Minnesota",
  "19": "Iowa",
  "29": "Missouri",
   "5": "Arkansas",
  "22": "Louisiana",
  "55": "Wisconsin",
  "17": "Illinois",
  "26": "Michigan",
  "18": "Indiana",
  "21": "Kentucky",
  "47": "Tennessee",
  "28": "Mississippi",
  "39": "Ohio",
   "1": "Alabama",
  "12": "Florida",
  "13": "Georgia",
  "45": "South Carolina",
  "37": "North Carolina",
  "51": "Virginia",
  "54": "West Virginia",
  "24": "Maryland",
  "10": "Delaware",
  "34": "New Jersey",
  "42": "Pennsylvania",
  "36": "New York",
   "9": "Connecticut",
  "44": "Rhode Island",
  "25": "Massachusetts",
  "33": "New Hampshire",
  "50": "Vermont",
  "23": "Maine",
   "2": "Alaska",
  "15": "Hawaii",
  "11": "Washington DC"
}

print old_dict
