# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Based_Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mentions_total', models.CharField(blank=True, max_length=45)),
                ('place_mention_total', models.CharField(blank=True, max_length=45)),
                ('length', models.CharField(blank=True, max_length=45)),
                ('source_size_ration', models.CharField(blank=True, max_length=45)),
                ('is_local', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=45)),
                ('source', models.CharField(max_length=45)),
                ('post_date', models.DateTimeField()),
                ('found_date', models.DateTimeField()),
                ('title', models.CharField(max_length=45)),
                ('aurthor', models.CharField(blank=True, max_length=45)),
                ('keywords', models.CharField(blank=True, max_length=45)),
                ('summary', models.CharField(blank=True, max_length=45)),
                ('text', models.TextField()),
                ('top_image', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles_Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('vote', models.CharField(blank=True, max_length=45)),
                ('who_acted', models.CharField(choices=[('SA', 'Senate Actions'), ('HA', 'House Actions'), ('FA', 'Fiscal Actions'), ('OA', 'Other Actions')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_mentions', models.CharField(blank=True, max_length=45)),
                ('mention_percentage', models.CharField(blank=True, max_length=45)),
                ('articles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_name_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_type', models.CharField(choices=[('HB', 'House Bill'), ('nHCR', 'House Concurrect Resolutions'), ('nHJR', 'House Joint Resolutions'), ('nHR', 'House Resolutions'), ('nSB', 'Senate Bills'), ('nSCR', 'Senate Concurrent'), ('nSJR', 'Senate Joint Resolutions'), ('nSR', 'Senate Resolutions')], max_length=100)),
                ('sponser', models.CharField(blank=True, max_length=45)),
                ('floor_sponser', models.CharField(blank=True, max_length=45)),
                ('substitute_sponser', models.CharField(blank=True, max_length=45)),
                ('last_action', models.CharField(blank=True, max_length=45)),
                ('last_location', models.CharField(blank=True, max_length=45)),
                ('text', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Committies',
            fields=[
                ('idcommitties', models.AutoField(primary_key=True, serialize=False)),
                ('committie', models.CharField(max_length=45)),
                ('overview', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('idlocations', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_mentions', models.CharField(blank=True, max_length=45)),
                ('mention_percentage', models.CharField(blank=True, max_length=45)),
                ('articles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles')),
                ('idlocations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Location')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('party', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('legislative_since', models.CharField(blank=True, max_length=45)),
                ('image', models.URLField(blank=True)),
                ('biography', models.CharField(blank=True, max_length=45)),
                ('district', models.CharField(blank=True, max_length=45)),
                ('counties', models.CharField(blank=True, max_length=45)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('profession_affiliations', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('home_phone', models.CharField(blank=True, max_length=45)),
                ('work_phone', models.CharField(blank=True, max_length=45)),
                ('cell', models.CharField(blank=True, max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('legislation_link', models.URLField(blank=True)),
                ('mailing_address', models.CharField(max_length=45)),
                ('committies', models.CharField(max_length=45)),
                ('social_media', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Bills')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.People')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Committies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcommitties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Committies')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.People')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mentions', models.CharField(blank=True, max_length=45)),
                ('mention_percentage', models.CharField(blank=True, max_length=45)),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.People')),
                ('person_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_share', models.CharField(blank=True, max_length=45)),
                ('reddit', models.CharField(blank=True, max_length=45)),
                ('total_count', models.CharField(blank=True, max_length=45)),
                ('articles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles')),
            ],
        ),
        migrations.AddField(
            model_name='bill_weight',
            name='bill_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Bills'),
        ),
        migrations.AddField(
            model_name='bill_status',
            name='bill_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Bills'),
        ),
        migrations.AddField(
            model_name='articles_bills',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Location'),
        ),
        migrations.AddField(
            model_name='article_person',
            name='articles_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles'),
        ),
        migrations.AddField(
            model_name='article_person',
            name='people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.People'),
        ),
        migrations.AddField(
            model_name='article_location',
            name='articles_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles'),
        ),
        migrations.AddField(
            model_name='article_location',
            name='idlocaiton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Location'),
        ),
        migrations.AddField(
            model_name='article_bill',
            name='articles_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles'),
        ),
        migrations.AddField(
            model_name='article_bill',
            name='bill_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Bills'),
        ),
        migrations.AddField(
            model_name='article_based_weights',
            name='articles_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Articles'),
        ),
    ]
