# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20170618_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='state',
            field=models.CharField(default='Utah', max_length=45),
            preserve_default=False,
        ),
    ]
