# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_people_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Found_Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
