# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_found_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_url',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
