# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_found_url_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_url',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='found_url',
            name='found_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='found_url',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='found_url',
            name='post_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='found_url',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='found_url',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='found_url',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='found_url',
            name='top_image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
